'use client'
import { useRef } from 'react'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

interface Result {
  id: string
  subject: string
  marks: number
  grade: string
  term: number
  year: number
}

interface Props {
  name: string
  admissionNo: string
  results: Result[]
}

export default function ReportCard({ name, admissionNo, results }: Props) {
  const ref = useRef<HTMLDivElement>(null)

  async function downloadPDF() {
    if (!ref.current) return
    const canvas = await html2canvas(ref.current, { scale: 2 })
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF('p', 'mm', 'a4')
    const width = pdf.internal.pageSize.getWidth()
    const height = (canvas.height * width) / canvas.width
    pdf.addImage(imgData, 'PNG', 0, 0, width, height)
    pdf.save(`${name}-report-card.pdf`)
  }

  const average = results.length > 0
    ? (results.reduce((sum, r) => sum + r.marks, 0) / results.length).toFixed(1)
    : '0'

  return (
    <div>
      <button
        onClick={downloadPDF}
        className="mb-6 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700 transition"
      >
        Download Report Card PDF
      </button>

      {/* Report Card Template */}
      <div ref={ref} className="bg-white p-8 rounded-2xl border max-w-2xl">
        {/* Header */}
        <div className="text-center border-b pb-6 mb-6">
          <div className="w-14 h-14 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-xl mx-auto mb-3">S</div>
          <h1 className="text-2xl font-bold text-gray-800">SchoolPulse Academy</h1>
          <p className="text-sm text-gray-500">Kampala, Uganda</p>
          <p className="text-lg font-semibold text-blue-600 mt-2">Student Report Card</p>
        </div>

        {/* Student Info */}
        <div className="grid grid-cols-2 gap-4 mb-6 bg-gray-50 rounded-xl p-4">
          <div>
            <p className="text-xs text-gray-500">Student Name</p>
            <p className="font-semibold text-gray-800">{name}</p>
          </div>
          <div>
            <p className="text-xs text-gray-500">Admission Number</p>
            <p className="font-semibold text-gray-800">{admissionNo}</p>
          </div>
          <div>
            <p className="text-xs text-gray-500">Academic Year</p>
            <p className="font-semibold text-gray-800">{results[0]?.year ?? '—'}</p>
          </div>
          <div>
            <p className="text-xs text-gray-500">Term</p>
            <p className="font-semibold text-gray-800">Term {results[0]?.term ?? '—'}</p>
          </div>
        </div>

        {/* Results Table */}
        <table className="w-full text-sm mb-6">
          <thead>
            <tr className="bg-blue-600 text-white">
              <th className="text-left px-4 py-2 rounded-tl-lg">Subject</th>
              <th className="text-left px-4 py-2">Marks</th>
              <th className="text-left px-4 py-2 rounded-tr-lg">Grade</th>
            </tr>
          </thead>
          <tbody>
            {results.map((r, i) => (
              <tr key={r.id} className={i % 2 === 0 ? 'bg-gray-50' : 'bg-white'}>
                <td className="px-4 py-2 text-gray-800">{r.subject}</td>
                <td className="px-4 py-2 text-gray-600">{r.marks}/100</td>
                <td className="px-4 py-2 font-semibold text-blue-600">{r.grade}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Average */}
        <div className="bg-blue-50 rounded-xl p-4 flex items-center justify-between">
          <p className="font-semibold text-gray-700">Overall Average</p>
          <p className="text-2xl font-bold text-blue-600">{average}%</p>
        </div>

        {/* Footer */}
        <div className="mt-8 pt-6 border-t flex justify-between text-xs text-gray-400">
          <p>Generated by SchoolPulse</p>
          <p>{new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  )
}